
title: Jekyll Theme - Lazy
description: It is minimal and lazy!

email: draconissickle@gmail.com

baseurl: "/jekyll-theme-lazy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: RadoslavStanchev
github_username:  RadoslavStanchev


# Build settings
future: true
markdown: kramdown
plugins:
  - jekyll-feed

destination: docs

exclude:
  # - Gemfile
  # - Gemfile.lock
  # - node_modules
  # - .gitignore
  # - scss
  # - gulpfile.js
  # - package.json
  # - package-lock.json
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss

